/**
 * SLATE DevOps OS — First-boot seed catalogue
 *
 * Everything in this file is DEMO content written only when no database exists
 * yet (fresh install). It was previously inlined in `lib/storage.ts`, which made
 * an 865-line module whose first ~260 lines were sample data.
 *
 * The two seed packages are deliberately kept: `normalizeDb()` re-seeds them for
 * any database written before the licensing feature existed, which would
 * otherwise leave /pricing and every install permanently empty.
 */

import type { StorageSchema } from "./models";

export const SEED_DATA: StorageSchema = {
  sites: [
    {
      id: "site_1",
      domain: "https://portal.clientalpha.com",
      path: "/public_html/app",
      framework: "WordPress",
      status: "ONLINE",
      dbStatus: "CONNECTED",
      dbSize: "48.2 MB",
      latency: "34ms",
      lastCommit: "b89a2f1",
      repo: "org/clientalpha-portal",
      handshakeToken: "slate_live_7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a",
      webhookSecret: "slate_sec_clientalpha_portal_1",
      lastDeployedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    },
    {
      id: "site_2",
      domain: "https://shop.apexgear.io",
      path: "/var/www/html/store",
      framework: "React / Node",
      status: "ONLINE",
      dbStatus: "CONNECTED",
      dbSize: "128.5 MB",
      latency: "52ms",
      lastCommit: "fa4c90e",
      repo: "org/apex-storefront",
      handshakeToken: "slate_live_4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b",
      webhookSecret: "slate_sec_apex_storefront_2",
      lastDeployedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    },
    {
      id: "site_3",
      domain: "https://demo.slate-saas.net",
      path: "/public_html",
      framework: "Laravel",
      status: "ONLINE",
      dbStatus: "CONNECTED",
      dbSize: "14.9 MB",
      latency: "29ms",
      lastCommit: "77cd10a",
      repo: "org/slate-demo-php",
      handshakeToken: "slate_live_1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c",
      webhookSecret: "slate_sec_slate_demo_php_3",
      lastDeployedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    },
  ],
  databases: [
    {
      id: "db_1",
      name: "clientalpha_portal_db",
      user: "calpha_usr",
      host: "127.0.0.1",
      port: 3306,
      mode: "mysql",
      size: "48.2 MB",
      tablesCount: 38,
      status: "ACTIVE",
      linkedSiteId: "site_1",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    },
    {
      id: "db_2",
      name: "apex_store_db",
      user: "apex_admin",
      host: "127.0.0.1",
      port: 3306,
      mode: "mysql",
      size: "128.5 MB",
      tablesCount: 64,
      status: "ACTIVE",
      linkedSiteId: "site_2",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    },
    {
      id: "db_3",
      name: "cpanel_slatedemo",
      user: "slatedemo_user",
      host: "cpanel.slate-saas.net",
      port: 3306,
      mode: "cpanel",
      size: "14.9 MB",
      tablesCount: 22,
      status: "ACTIVE",
      linkedSiteId: "site_3",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    },
  ],
  deployments: [
    {
      id: "dep_1",
      siteId: "site_1",
      domain: "https://portal.clientalpha.com",
      repo: "org/clientalpha-portal",
      commitSha: "b89a2f1",
      actor: "devops-lead",
      status: "SUCCESS",
      duration: "4.2s",
      timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      logs: [
        "[05:25:01] INITIATING ZERO-TOUCH CI/CD PIPELINE FOR portal.clientalpha.com",
        "[05:25:02] Authenticating via SLATE agent handshake token... SUCCESS [200 OK]",
        "[05:25:02] Target runtime verified: PHP 8.2 / PDO MySQL / ZipArchive",
        "[05:25:03] Pulling commit b89a2f1 from org/clientalpha-portal (branch: main)",
        "[05:25:04] Synchronizing release payload to /public_html/app...",
        "[05:25:04] Atomic file swap and cache invalidation completed.",
        "[05:25:05] Target environment responded 200 OK. Health check latency: 34ms.",
        "[05:25:05] DEPLOYMENT COMPLETE (Duration: 4.2s) - Status: ONLINE",
      ],
    },
    {
      id: "dep_2",
      siteId: "site_2",
      domain: "https://shop.apexgear.io",
      repo: "org/apex-storefront",
      commitSha: "fa4c90e",
      actor: "frontend-team",
      status: "SUCCESS",
      duration: "6.8s",
      timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      logs: [
        "[04:10:10] INITIATING CI/CD BUILD FOR shop.apexgear.io",
        "[04:10:11] Target node: /var/www/html/store verified.",
        "[04:10:13] Building React/Next.js standalone bundle (fa4c90e)...",
        "[04:10:15] Deploying artifact archive to edge cluster...",
        "[04:10:16] Zero-downtime container hot-reload executed.",
        "[04:10:17] Health probe: Latency 52ms. Status: ONLINE",
      ],
    },
  ],
  settings: {
    githubTokenEncrypted: "",
    githubUsername: "slate-devops-admin",
    githubAvatar: "",
    autoSyncInterval: 30,
    notifyOnDeploy: true,
  },
  migrations: [
    {
      id: "mig_sample_1",
      title: "Live Production Cluster Sync (cPanel US -> EU)",
      source: {
        serverName: "cPanel Node US-East (Old Host)",
        cpanelHost: "cpanel.useast-legacy.net",
        cpanelPort: 2083,
        cpanelUser: "legacyalpha",
        cpanelApiToken: "CPANEL_TOKEN_ALPHA_US_SEC_99",
        fileManagerPath: "/home/legacyalpha/public_html",
        siteUrl: "https://legacy-portal.clientalpha.com",
        dbHost: "localhost",
        dbName: "legacyalpha_wp",
        dbUser: "legacyalpha_usr",
        dbPass: "masked",
      },
      destination: {
        serverName: "cPanel Node EU-Central (Target Cloud)",
        cpanelHost: "cpanel.eucloud-speed.net",
        cpanelPort: 2083,
        cpanelUser: "apexcloud",
        cpanelApiToken: "CPANEL_TOKEN_EU_SPEED_88",
        fileManagerPath: "/home/apexcloud/public_html",
        siteUrl: "https://portal.clientalpha.com",
        dbHost: "localhost",
        dbName: "apexcloud_wp_mirror",
        dbUser: "apexcloud_usr",
        dbPass: "masked",
      },
      options: {
        syncFiles: true,
        syncDatabase: true,
        replaceDomainUrls: true,
        fixFilePermissions: true,
      },
      status: "COMPLETED",
      progress: 100,
      totalFiles: 4218,
      transferredFiles: 4218,
      totalDbTables: 38,
      transferredDbTables: 38,
      currentStep: "Migration finished successfully. Target site is verified mirror copy.",
      logs: [
        { timestamp: "10:14:02", message: "Handshake verified with Source cPanel Node US-East.", type: "success" },
        { timestamp: "10:14:05", message: "Handshake verified with Destination cPanel Node EU-Central.", type: "success" },
        { timestamp: "10:14:15", message: "Database exported (legacyalpha_wp: 38 tables, 64.2 MB).", type: "info" },
        { timestamp: "10:14:35", message: "SQL search-and-replace applied: legacy-portal.clientalpha.com -> portal.clientalpha.com", type: "info" },
        { timestamp: "10:14:55", message: "Database imported into Destination (apexcloud_wp_mirror).", type: "success" },
        { timestamp: "10:15:20", message: "File tree compressed into stream bundle (4,218 files).", type: "info" },
        { timestamp: "10:16:40", message: "All files extracted to destination /home/apexcloud/public_html.", type: "success" },
        { timestamp: "10:16:48", message: "Configured wp-config.php / .env credentials and file permissions (0644/0755).", type: "success" },
      ],
      createdAt: "2026-09-11T10:14:00Z",
      completedAt: "2026-09-11T10:16:50Z",
    },
  ],
  packages: [
    {
      id: "pkg_business_ops",
      slug: "business-ops",
      name: "Business Operations",
      description: "Core + Booking + Membership + Stripe Payment",
      is_active: true,
      sort_order: 1,
      pluginSet: ["booking", "membership", "stripe-payment"],
      restrictions: [
        { match: "admin/settings.php", mode: "block" },
        { match: "admin/plugins.php", mode: "block" },
        { match: "plugins/booking/admin/new.php", mode: "block" },
        { match: "plugins/booking/admin/settings.php", mode: "block" },
        { match: "plugins/stripe-payment/admin/*", mode: "block" },
        { match: "plugins/booking/admin/appointments.php", mode: "readonly" },
        { match: "plugins/booking/admin/customers.php", mode: "readonly" },
        { match: "plugins/membership/admin/members.php", mode: "readonly" },
      ],
      pricing: {
        monthly_cents: 2900,
        yearly_cents: 29000,
        lifetime_cents: 99000,
        currency: "USD",
      },
      createdAt: "2026-01-01T00:00:00Z",
      githubRef: "v1.4.0",
    },
    {
      id: "pkg_coaching_suite",
      slug: "coaching-suite",
      name: "Coaching Platform",
      description: "Core + Coaching + Forms + Stripe Payment + MCP Gateway",
      is_active: true,
      sort_order: 2,
      pluginSet: ["coaching", "forms", "stripe-payment", "mcp-gateway"],
      restrictions: [
        { match: "admin/settings.php", mode: "block" },
        { match: "admin/plugins.php", mode: "block" },
        { match: "plugins/coaching/admin/new.php", mode: "block" },
        { match: "plugins/coaching/admin/settings.php", mode: "block" },
        { match: "plugins/forms/admin/*", mode: "block" },
        { match: "plugins/stripe-payment/admin/*", mode: "block" },
        { match: "plugins/coaching/admin/sessions.php", mode: "readonly" },
        { match: "plugins/coaching/admin/clients.php", mode: "readonly" },
        { match: "admin/contact_forms.php", mode: "readonly" },
      ],
      pricing: {
        monthly_cents: 4900,
        yearly_cents: 49000,
        lifetime_cents: 199000,
        currency: "USD",
      },
      createdAt: "2026-01-01T00:00:00Z",
      githubRef: "v1.4.0",
    },
  ],
  orders: [],
  licenses: [],
};

/** Deep clone so callers can mutate a seed without corrupting the template. */
export function cloneSeed(): StorageSchema {
  return JSON.parse(JSON.stringify(SEED_DATA)) as StorageSchema;
}